name: CI-CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install 'dvc[s3]'
        pip install dagshub

    - name: Configure DVC remote
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      run: |
        dvc remote add -f -d myremote s3://spotify-hybrid-recommender-system
        dvc remote modify myremote access_key_id $AWS_ACCESS_KEY_ID
        dvc remote modify myremote secret_access_key $AWS_SECRET_ACCESS_KEY
        dvc remote modify myremote region ap-southeast-2

    - name: Pull DVC-tracked data
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
      run: |
        echo "Running: dvc pull -v"
        dvc pull -v
        echo "--- DVC Status ---"
        dvc status -v
        echo "--- Cache Check ---"
        du -sh .dvc/cache || echo "No DVC cache found"
        echo "--- File Check ---"
        ls -lh data/raw/ || echo "data/raw/ folder not found"
        ls -lh "data/raw/Music Info.csv" || echo "Music Info.csv not found"

    - name: Run DVC Pipeline
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
      run: dvc repro

    - name: Push DVC-tracked data to remote
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
      run: dvc push

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add changes to Git
      run: git add .

    - name: Commit changes
      if: ${{ github.actor != 'github-actions[bot]' }}
      run: |
        git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"

    - name: Push changes
      if: ${{ github.actor != 'github-actions[bot]' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin ${{ github.ref_name }}

    - name: Install test dependencies
      run: pip install pytest

    - name: Test App
      run: |
        pytest test_app.py

    - name: Stop Streamlit app
      run: |
        pkill -f "streamlit run" || echo "No streamlit app to kill"
